### PR TITLE
Adding Akeeba Release System

### PR DESCRIPTION
**Pull request by svanschu**
I don't included the download folder, because it is customize able, so you don't know where the folder lies ...

I don't know why all those cli stuff happened ... I didn't touched them ...

### CODE REVIEW

**Comment by fastslack** [comment]
HI!

First thanks for the patch. Can you remove the cli/extensions changes? so i can to merge your patch without change the cli/extensions symlinks.

Thanks

**Comment by svanschu** [comment]
As you see I tried to revert those, but it didn't worked. I'm trying to understand what there was happening so I can revert those ... Have you any idea?

**Comment by mahagr** [comment]
I think it might be easiest to drop this pull request, delete your repository and try it again (by committing only the changed files).

**Comment by fastslack** [comment]
Yes, you must to commit specifying the directory where the changes were made. Ex:

```
git commit -m "super change" trunk/admin/extensions/
```

**Comment by svanschu** [comment]
I've deleted now the fork and made a new one. I pulled the fresh fork and git wanted to push again the cli/extension folder. But now I moved those files to another changelist, so they get ignored ...

**Pull request closed without merging**
