### PR TITLE
Update Kunena component migration

### PR DESCRIPTION
**Pull request by mahagr**
- Update Finnish translation 
- Update migration for Kunena component 
- Find j25upgrade.xml file instead of j16upgrade.xml from extensions

### CODE REVIEW

**Comment by mahagr** [comment]
@fastslack, can you check this pull request?

**Comment by fastslack** [comment]
@mahagr Yes, testing right now...

**Comment by fastslack** [comment]
I fixed some small issues, but it still not working.. No error, but not content migrated.. seems that the default schema is installed again after Kunena installation on Joomla 2.5

``` diff
diff --git a/trunk/admin/extensions/com_kunena.php b/trunk/admin/extensions/com_kunena.php
index 6c7b6a1..56d2ab6 100644
--- a/trunk/admin/extensions/com_kunena.php
+++ b/trunk/admin/extensions/com_kunena.php
@@ -46,7 +46,7 @@ class jUpgradeComponentKunena extends jUpgradeExtensions {
                if (file_exists(JPATH_SITE.'/includes/version.php')) require_once JPATH_SITE.'/includes/version.php';

                require_once $this->api;
-               if (class_exists('Kunena') && version_compare(Kunena:version(), '1.6.4', '>=')) return true;
+               if (class_exists('Kunena') && version_compare(Kunena::version(), '1.6.4', '>=')) return true;

                return false;
        }
@@ -129,25 +129,6 @@ class jUpgradeComponentKunena extends jUpgradeExtensions {
        }

        /**
-        * Migrate custom information.
-        *
-        * This function gets called after all folders and tables have been copied.
-        *
-        * If you want to split this task into smaller chunks,
-        * please store your custom state variables into $this->state and return false.
-        * Returning false will force jUpgrade to call this function again,
-        * which allows you to continue import by reading $this->state before continuing.
-        *
-        * @return      boolean Ready (true/false)
-        * @since       1.1.0
-        * @throws      Exception
-        */
-       protected function migrateExtensionCustom()
-       {
-               return $this->_fixBrokenMenu();
-       }
-
-       /**
         * Copy kunena_categories table from old site to new site.
         *
         * You can create custom copy functions for all your tables.
@@ -215,8 +196,6 @@ class jUpgradeComponentKunena extends jUpgradeExtensions {
         * @throws      Exception
         */
        protected function migrateExtensionCustom() {
-               require_once $this->api;
-
                // Need to initialize application
                jimport ('joomla.environment.uri');
                $app = JFactory::getApplication('administrator');
```

**Comment by mahagr** [comment]
I'll check it soon; I forgot that my local version used j25upgrade.xml inside our component and not the default one...

**Pull request merged**
